Repository IBM/pytorchpipe, pull requests merged in 2019-04, with the labels that each got.

#9 Add broadcast functionality to FFN component
  configs/default/components/models/feed_forward_network.yml
  ptp/components/models/feed_forward_network.py
Labels: enhancement

#13 RNN autoregression fix
  .gitignore
  configs/default/components/models/recurrent_neural_network.yml
  configs/wikitext/wikitext_language_modeling_seq2seq.yml
  configs/wikitext/wikitext_language_modeling_seq2seq_simple.yml
  ptp/components/models/recurrent_neural_network.py
  ptp/components/models/seq2seq_rnn.py
Labels: bug

#17 Replace urllibs by requests for data download
  ptp/components/utils/io.py
  setup.py
Labels: bug, enhancement

#18 Add fixed padding option to sentence_embeddings, sentence_indexer
  configs/default/components/models/sentence_embeddings.yml
  configs/default/components/text/sentence_indexer.yml
  ptp/components/models/sentence_embeddings.py
  ptp/components/text/sentence_indexer.py
  ptp/components/utils/word_mappings.py
Labels: enhancement

#21 vqa_mde y/n fix
  configs/vqa_med_2019/c2_classification/c2_word_answer_onehot_bow.yml
  configs/vqa_med_2019/c4_classification/c4_word_answer_onehot_bow.yml
  ptp/components/problems/image_text_to_class/vqa_med_2019.py
Labels: bug

#15 (Depends on PR #18 #17) RNN Decoder with attention
  configs/default/components/models/attn_decoder_rnn.yml
  configs/default/components/problems/text_to_text/translation_pairs.yml
  configs/translation/eng_fra_translation_enc_attndec.yml
  configs/wikitext/wikitext_language_modeling_encoder_attndecoder.yml
  ptp/components/models/__init__.py
  ptp/components/models/attn_decoder_rnn.py
  ptp/components/problems/text_to_text/__init__.py
  ptp/components/problems/text_to_text/translation_pairs.py
Labels: enhancement

#22 Relational Network refactor
  configs/default/components/models/vqa/relational_network.yml
  configs/vqa_med_2019/c2_classification/c2_classification_all_rnn_vgg16_relational_net.yml
  configs/vqa_med_2019/c4_classification/c4_enc_attndec.yml
  ptp/components/models/feed_forward_network.py
  ptp/components/models/vqa/relational_network.py
Labels: enhancement

#27 Add support for <EOS> token
  configs/default/components/losses/nll_loss.yml
  configs/default/components/models/sentence_embeddings.yml
  configs/default/components/text/label_indexer.yml
  configs/default/components/text/sentence_indexer.yml
  configs/default/components/text/sentence_one_hot_encoder.yml
  configs/default/components/text/word_decoder.yml
  configs/vqa_med_2019/c4_classification/c4_enc_attndec.yml
  ptp/components/losses/nll_loss.py
  ptp/components/mixins/word_mappings.py
  ptp/components/text/sentence_indexer.py
  ptp/components/utils/word_mappings.py
Labels: enhancement

#32 Add option to ignore words in BLEU
  configs/default/components/publishers/bleu_statistics.yml
  ptp/components/publishers/bleu_statistics.py
Labels: bug, enhancement

#35 Remove truncation in reversed SentenceIndexer
  ptp/components/text/sentence_indexer.py
Labels: bug
